### ISSUE TITLE
Lock Screen

### ISSUE THREAD

**Issue by SaxatB** [DanL2015/AwesomeWM#2]
The lock screen works fine at first but if it is on for long enough it stops working and allows to use the system without any hesitation

**Comment by danxliu** [comment]
Does the lock screen disappear or something after a while?

**Comment by SaxatB** [comment]
> Does the lock screen disappear or something after a while?

It launched normally at first. I was away for a  while and when I returned the lock circle and the clock were gone. Then I switched workspaces the bar returned and I could access my desktop normally.

**Comment by SaxatB** [comment]
> > Does the lock screen disappear or something after a while?
> 
> It launched normally at first. I was away for a while and when I returned the lock circle and the clock were gone. Then I switched workspaces the bar returned and I could access my desktop normally.

![initially](https://github.com/DanL2015/AwesomeWM/assets/107102227/554021cc-7d3b-4bf3-8510-30c201e90038)
This is how it looks at the beginning. Everything is working fine but

![after](https://github.com/DanL2015/AwesomeWM/assets/107102227/3089db11-952d-4a44-bb38-d4c5a96af1bc)
after some time it suddenly switches to this and now I can access my desktop normally.

EDIT - This seems to happen when memory cleaning script is set to run every 5 seconds, setting it to 30 solved the issue for me
